sudo: required

services:
  - docker

before_install:
  - docker build  -t  anchalke/frontend:1.0  -f  ./frontend/Dockerfile.dev ./frontend
  
script:
  - docker run  anchalke/frontend:1.0 npm run test  --  --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app:  "frontend"
  env:  "Frontend-env"
  bucket_name:  "elasticbeanstalk-us-east-2-056054572741"
  bucket_path:  "frontend"
  on:
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"